GET http://localhost:3000/books
###

GET http://localhost:3000/books/5
###

GET http://localhost:3000/authors
###

GET http://localhost:3000/authors/1
###

GET http://localhost:3000/bookauthors/4
###

GET http://localhost:3000/publishers
###

GET http://localhost:3000/publishers/2
###

GET http://localhost:3000/book-types
###

GET http://localhost:3000/book-types/1
###

GET http://localhost:3000/search/jav
###

GET http://localhost:3000/users/bibek@gmail.com
###

POST http://localhost:3000/books
Content-Type: application/json

{
    "name": "C#"
}
###


POST http://localhost:3000/users
Content-Type: application/json

{
     "name":"Bibek Neupane",
      "email":"bibek@gmail.com",
      "username":"bibek_neupane",
      "password": "abcd",
      "dob":"2022/01/01"
}
###

PUT http://localhost:3000/books/1
Content-Type: application/json

{
    "name": "javascript"
}
###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.bmJpYmVrMTNAZ21haWwuY29t.XQj8o1C076xZIMAm78ODamTUJqBZrMYPNrqlsPcVzxs"
}
###


GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6e30sImlhdCI6MTY0NzM5NDg2OCwiZXhwIjoxNjQ3Mzk0ODk4fQ.vI3byypbXZBzabkPyBkw13VLWfxuYUMdZ4dt9jGBWcQ
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}
###

GET http://localhost:4000/users/login
Content-Type: application/json

{
    "email" :"nbibek13@gmail.com",
    "password": "Hahaha@321"
}
###



POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "bibek Nuepane",
    "email" :"nbibek13@gmail.com",
    "password": "Hahaha@321"
}
###



DELETE http://localhost:3000/delete-book/3029
###
DELETE http://localhost:3000/delete/book-type/1