PUT http://localhost:3000/books
Content-Type: application/json

{
    "a":1,
    "b":2
}
###

GET http://localhost:3000/books/4056
###

GET http://localhost:3000/authors
###

GET http:/localhost:3000/authors/1
###

GET http://localhost:3000/bookauthors/4
###

GET http://localhost:3000/publishers
###

GET http://localhost:3000/publishers/2
###

GET http://localhost:3000/book-types
###

GET http://localhost:3000/book-types/1
###

GET http://localhost:3000/search/jav
###


POST http://localhost:3000/books
Content-Type: application/json

{
    "name": "C#"
}
###

POST http://localhost:3000/cart
Content-Type: application/json

{
    "id": 4060
}

###


POST http://localhost:3000/books
Content-Type: application/json

{
    "bookName" : "Java",
    "year" : "2000",
    "pages" : 200,
    "isbn" : "adsasdasd",
    "edition" : 3,
    "authors" : "1,2",
    "publisher" : 1,
    "bookType" : 1,
    "price" : "600"
}
###


POST http://localhost:3000/users
Content-Type: application/json

{
     "name":"Bibek Neupane",
      "email":"bibek@gmail.com",
      "username":"bibek_neupane",
      "password": "abcd",
      "dob":"2022/01/01"
}
###

PUT http://localhost:3000/books/1
Content-Type: application/json

{
    "name": "javascript"
}
###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.bmJpYmVrQGdtYWlsLmNvbQ.B6IlGZ0Z1FPKpy1lgT0yaMCCaNDgjw7nmi4Rnx-2e0Q"
}
###


GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5iaWJla0BnbWFpbC5jb20iLCJpYXQiOjE2NDgzOTcxNjIsImV4cCI6MTY0ODM5NzE4Mn0.Spxr0UfwDctRrFGc_4aUlEoTjFGkChsTodrHtjqEaUU
###

GET http://localhost:4000/users/login
Content-Type: application/json

{
    "email" :"sakar@gmail.com",
    "password": "1234"
}
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.bmJpYmVrQGdtYWlsLmNvbQ.B6IlGZ0Z1FPKpy1lgT0yaMCCaNDgjw7nmi4Rnx-2e0Q"
}
###



POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Bibek Neupane",
    "email" :"nbibek@gmail.com",
    "password": "Hahaha@321",
    "dob": "2022-02-25",
    "username":"bibekneupane"
}
###

DELETE http://localhost:3000/delete-book/3029
###
DELETE http://localhost:3000/delete/booktype/1 
###
DELETE http://localhost:3000/delete/author/1
###
GET http://localhost:3000/users